services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp
    environment:
      - CGO_ENABLED=0
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=qr_order_db
    depends_on:
      db:
        condition: service_healthy
    command: air -c .air.toml

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=qr_order_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [
        "CMD-SHELL",
        "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 120s

volumes:
  mysql_data:
